language: cpp
compiler:
  - gcc
  - clang
before_install:
  - env
  - uname -a
install:
  - git clone https://github.com/msgpack/msgpack-c.git
  - pushd msgpack-c && ./bootstrap && ./configure && make && sudo make install && popd
  - sudo ldconfig
script:
  - ./waf configure
  - ./waf build
  - ./waf build --checkall
branches:
  only:
    - master
notifications:
  email: false
